version: "3"

services:
  php:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app

  queue:
    build: ./.docker/php
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "php artisan queue:work"

  nginx:
    image: nginx:alpine
    volumes:
      - .:/app:ro
    working_dir: /app
    depends_on:
      - php

  composer:
    image: composer:latest
    volumes:
      - .:/app
    environment:
      TERM: "xterm-256color"

  nodejs:
    image: node:17-alpine3.15
    volumes:
      - .:/usr/app
    working_dir: /usr/app
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
